/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cleansine_sound_provider_SimpleMixerProvider */

#ifndef _Included_com_cleansine_sound_provider_SimpleMixerProvider
#define _Included_com_cleansine_sound_provider_SimpleMixerProvider
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_ERROR
#define com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_ERROR 0L
#undef com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_WARN
#define com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_WARN 1L
#undef com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_INFO
#define com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_INFO 2L
#undef com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_DEBUG
#define com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_DEBUG 3L
#undef com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_TRACE
#define com_cleansine_sound_provider_SimpleMixerProvider_LIB_LOG_LEVEL_TRACE 4L
#undef com_cleansine_sound_provider_SimpleMixerProvider_MAX_RATE_LIMIT
#define com_cleansine_sound_provider_SimpleMixerProvider_MAX_RATE_LIMIT 384000L
#undef com_cleansine_sound_provider_SimpleMixerProvider_MAX_CHANNELS_LIMIT
#define com_cleansine_sound_provider_SimpleMixerProvider_MAX_CHANNELS_LIMIT 8L
/*
 * Class:     com_cleansine_sound_provider_SimpleMixerProvider
 * Method:    nInit
 * Signature: (ILjava/lang/String;[I[III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cleansine_sound_provider_SimpleMixerProvider_nInit
  (JNIEnv *, jclass, jint, jstring, jintArray, jintArray, jint, jint);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixerProvider
 * Method:    nGetMixerCnt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cleansine_sound_provider_SimpleMixerProvider_nGetMixerCnt
  (JNIEnv *, jclass);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixerProvider
 * Method:    nCreateMixerInfo
 * Signature: (I)Lcom/cleansine/sound/provider/SimpleMixerInfo;
 */
JNIEXPORT jobject JNICALL Java_com_cleansine_sound_provider_SimpleMixerProvider_nCreateMixerInfo
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
