/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cleansine_sound_provider_SimpleMixerProvider */

#ifndef _Included_com_cleansine_sound_provider_SimpleMixerProvider
#define _Included_com_cleansine_sound_provider_SimpleMixerProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cleansine_sound_provider_SimpleMixerProvider
 * Method:    nInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_cleansine_sound_provider_SimpleMixerProvider_nInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixerProvider
 * Method:    nGetMixerCnt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cleansine_sound_provider_SimpleMixerProvider_nGetMixerCnt
  (JNIEnv *, jclass);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixerProvider
 * Method:    nCreateMixerInfo
 * Signature: (I)Lcom/cleansine/sound/provider/SimpleMixerInfo;
 */
JNIEXPORT jobject JNICALL Java_com_cleansine_sound_provider_SimpleMixerProvider_nCreateMixerInfo
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
