/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cleansine_sound_provider_SimpleMixer */

#ifndef _Included_com_cleansine_sound_provider_SimpleMixer
#define _Included_com_cleansine_sound_provider_SimpleMixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nGetFormats
 * Signature: (Ljava/lang/String;ZLjava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nGetFormats
  (JNIEnv *, jclass, jstring, jboolean, jobject);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nStart
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nStart
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nStop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nStop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nOpen
 * Signature: (Ljava/lang/String;ZIIIIIZZI)J
 */
JNIEXPORT jlong JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nOpen
  (JNIEnv *, jclass, jstring, jboolean, jint, jint, jint, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nClose
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nClose
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nRead
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nRead
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nWrite
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nWrite
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nGetBufferBytes
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nGetBufferBytes
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nGetAvailBytes
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nGetAvailBytes
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nDrain
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nDrain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nFlush
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nFlush
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_cleansine_sound_provider_SimpleMixer
 * Method:    nGetBytePos
 * Signature: (JZJ)J
 */
JNIEXPORT jlong JNICALL Java_com_cleansine_sound_provider_SimpleMixer_nGetBytePos
  (JNIEnv *, jclass, jlong, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
